version: '3'
services:
  fuseki:
    image: stain/jena-fuseki:latest
    container_name: fuseki
    ports:
      - "3030:3030"
    environment:
      - ADMIN_PASSWORD=admin123
    volumes:
      - ./fuseki-data:/fuseki  # ホストの./fuseki-dataディレクトリをコンテナの/fusekiにマウント
    command: ["/jena-fuseki/fuseki-server", "--update", "--loc=/fuseki/databases/ds", "/ds"]  # ファイルベースのデータセット
  webapp:
    build: ./webapp
    container_name: webapp
    depends_on:
      - fuseki
    ports:
      - "8080:8080"
    environment:
      - FUSEKI_URL=http://fuseki:3030/ds
      - NODE_ENV=production