version: '3'
services:
  fuseki:
    image: jena/fuseki:latest
    container_name: fuseki
    ports:
      - "3030:3030"
    environment:
      - JVM_ARGS=-Xmx2g
    command: ["--mem", "--update", "/ds"]
  webapp:
    build: ./webapp
    container_name: webapp
    depends_on:
      - fuseki
    ports:
      - "8080:8080"
    environment:
      - FUSEKI_URL=http://fuseki:3030/ds
      - NODE_ENV=production